[package]
name = "perflite_wasm"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "WASM module for PerfLite"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.88"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1 